### ISSUE TITLE
create topic /article

### ISSUE THREAD

**Issue by mexican75** [luchianenco/symfony-api-sandbox#1]
Hi Serghei,
I'm Ramon from Reuter.
I'm having trouble with the create routes I tried various request structures but no success.
{
	"title" : "test",
	"author" : "yo mero",
	"text" : "asdjkfnlkasjnldkj ajkpioasj pojsaf p",
	"topic_id" : 1  // topic, topic title 
}

**Comment by luchianenco** [comment]
Hi @mexican75,
I forgot to remove second form submit after refactoring, so it was throwing an exception.

this one used for Article creation
{"article":{"title":"1", "author":"2", "text":"text", "topic":4}}

for topic:
{"topic":{"title":"1"}}

**Comment by mexican75** [comment]
I looked my self for the error but I over saw it. thanks for the rapid response

**Comment by luchianenco** [comment]
added unit testing for TopicService, and some refactoring of controller status codes
